project:
  type: website
  title: "biostat777-intro-zhenlong-zhang"

website:
  title: "Zhenlong Zhang's Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: example-analysis.qmd
        text: Example Analysis
        href: part1.qmd
        text: Brand Reflection
      - href: part3.qmd
        text: Command Line Exercises

format:
  html:
    theme: cosmo  
    toc: true    

editor: visual
